### ISSUE TITLE
"Missing exports condition" warning with vite-plugin-svelte

### ISSUE THREAD

**Issue by ornato-t** [metonym/svelte-geolocation#6]
When bundling with vite@5.0.9 and @sveltejs/vite-plugin-svelte@3.0.1 (after having updated to SvelteKit 2), I've been getting the following Vite warning:

> [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.
> 
> svelte-geolocation@0.3.0
> 
> Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

Reading from that link, it looks like a small change to the `package.json` file should fix this. My app runs just fine even with the warning, but according to the link this current structure is deprecated and support for it might be removed in the future.

Note: I have been getting this same warning with your [svelte-search](https://github.com/metonym/svelte-search) library, but opening two separate issues for the same problem sounds a bit overkill. I'd appreciate it if you could update both.

**Comment by metonym** [comment]
Thanks for reporting, will take a pass at resolving these warnings.

**Comment by DavyK17** [comment]
Also just ran into this issue. Looks like it hasn't been resolved yet.

**Comment by metonym** [comment]
The package is updated with an exports map in [v1.0.0](https://github.com/metonym/svelte-geolocation/releases/tag/v1.0.0)
